# Setup

In [1]:
import numpy as np
import pandas as pd

In [2]:
import sys
sys.path.append(r"/")
sys.path.append(r"/")

from provenance_coo import Provenance, print_prov_result, trace

prov = Provenance()

# Dataset
The [German Credit Dataset](https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data) uses a set of attributes to predict whether an individual's credit risk is good or bad. 

Input:  1000 records, 20 features (13 categorical, 7 numerical)

Target: 1000 records, 2 categories (1 = Good, 2 = Bad)

In [3]:
# Load dataset
from ucimlrepo import fetch_ucirepo
statlog_german_credit_data = fetch_ucirepo(id=144)
X = statlog_german_credit_data.data.features
y = statlog_german_credit_data.data.targets

variables = statlog_german_credit_data.variables
categorical_features = variables.loc[(variables['type'] != 'Integer') & (variables['role'] == 'Feature'), 'name'].tolist()
numerical_features = variables.loc[variables['type'] == 'Integer', 'name'].tolist()

In [4]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Pipeline

In [5]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# X_train_scaled = X_train.copy()
# X_train_scaled[numerical_features] = scaler.fit_transform(X_train_scaled[numerical_features])

# from sklearn.preprocessing import OneHotEncoder
# encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
# X_train_categorical_encoded = encoder.fit_transform(X_train_scaled[categorical_features])  # np.ndarray
# print(X_train_categorical_encoded)
# # Convert back to DataFrame
# encoded_features = encoder.get_feature_names_out()
# X_train_categorical_encoded = pd.DataFrame(X_train_categorical_encoded, columns=encoded_features, index=X_train_scaled.index)
# X_train_encoded = pd.concat([X_train_scaled.drop(columns=categorical_features), X_train_categorical_encoded], axis=1)

# from sklearn.feature_selection import SelectKBest, chi2
# k = 40
# selector = SelectKBest(score_func=chi2, k=k)
# X_train_categorical_selected = selector.fit_transform(X_train_categorical_encoded, y_train)
# selected_features = pd.Index(encoded_features)[selector.get_support()].to_list()

# X_train_categorical_selected = selector.transform(X_train_encoded[encoded_features])
# # Convert back to DataFrame
# selected_features = pd.Index(encoded_features)[selector.get_support()].to_list()
# X_train_selected = X_train_encoded[numerical_features + selected_features]

# from imblearn.over_sampling import RandomOverSampler  
# ros = RandomOverSampler(random_state=42)
# X_train_resampled, y_train_resampled = ros.fit_resample(X_train_selected, y_train)

# from sklearn.ensemble import RandomForestClassifier
# clf = RandomForestClassifier(n_estimators=100, random_state=42)
# clf.fit(X_train_resampled, y_train_resampled.squeeze())

In [6]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.compose import ColumnTransformer
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import RandomOverSampler
from sklearn.ensemble import RandomForestClassifier

numerical_pipeline = Pipeline([
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline([
    ('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore')),
    ('selector', SelectKBest(score_func=chi2, k=40))
])

preprocessor = ColumnTransformer([
    ('num', numerical_pipeline, numerical_features),
    ('cat', categorical_pipeline, categorical_features)
])

model = Pipeline([
    ('preprocessor', preprocessor),
    ('sampler', RandomOverSampler(random_state=42)),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

model.fit(X_train, y_train.squeeze())

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['Attribute2', 'Attribute5',
                                                   'Attribute8', 'Attribute11',
                                                   'Attribute13', 'Attribute16',
                                                   'Attribute18']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False)),
                                                                  ('selector',
                                                                   SelectKBest(k=40,
                                                                               score_func=<function chi2 at 0x00000233B88C8E00>))]),
                                                  ['Attribute1', 'Attribute3',
                                                   'Attribute4', 'Attribute6',
                                                   'Attribute7', 'Attribute9',
                                                   'Attribute10', 'Attribute12',
                                                   'Attribute14', 'Attribute15',
                                                   'Attribute17', 'Attribute19',
                                                   'Attribute20'])])),
                ('sampler', RandomOverSampler(random_state=42)),
                ('classifier', RandomForestClassifier(random_state=42))])

# Test

In [7]:
X_test

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,Attribute11,Attribute12,Attribute13,Attribute14,Attribute15,Attribute16,Attribute17,Attribute18,Attribute19,Attribute20
521,A11,18,A32,A43,3190,A61,A73,2,A92,A101,2,A121,24,A143,A152,1,A173,1,A191,A201
737,A11,18,A32,A40,4380,A62,A73,3,A93,A101,4,A123,35,A143,A152,1,A172,2,A192,A201
740,A11,24,A31,A40,2325,A62,A74,2,A93,A101,3,A123,32,A141,A152,1,A173,1,A191,A201
660,A13,12,A32,A43,1297,A61,A73,3,A94,A101,4,A121,23,A143,A151,1,A173,1,A191,A201
411,A14,33,A34,A41,7253,A61,A74,3,A93,A101,2,A123,35,A143,A152,2,A174,1,A192,A201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,A14,24,A32,A43,3235,A63,A75,3,A91,A101,2,A123,26,A143,A152,1,A174,1,A192,A201
332,A12,60,A32,A40,7408,A62,A72,4,A92,A101,2,A122,24,A143,A152,1,A174,1,A191,A201
208,A11,24,A32,A49,6568,A61,A73,2,A94,A101,2,A123,21,A142,A152,1,A172,1,A191,A201
613,A11,24,A31,A41,3632,A61,A73,1,A92,A103,4,A123,22,A141,A151,1,A173,1,A191,A202
78,A14,54,A30,A41,9436,A65,A73,2,A93,A101,2,A122,39,A143,A152,1,A172,2,A191,A201

In [8]:
y_test

     class
521      2
737      1
740      1
660      1
411      1
..     ...
408      1
332      2
208      1
613      1
78       1

[200 rows x 1 columns]

# 1. Data Transformation

Standardization for numerical features.

In [9]:
scaler = model.named_steps['preprocessor'].named_transformers_['num'].named_steps['scaler']
X_test_numerical_scaled = scaler.transform(X_test[numerical_features])
# Convert back to DataFrame
X_test_scaled = pd.DataFrame(
    np.hstack([X_test_numerical_scaled, X_test[categorical_features]]),
    columns=numerical_features + categorical_features,
    index=X_test.index
)
X_test_scaled

,Attribute2,Attribute5,Attribute8,Attribute11,Attribute13,Attribute16,Attribute18,Attribute1,Attribute3,Attribute4,Attribute6,Attribute7,Attribute9,Attribute10,Attribute12,Attribute14,Attribute15,Attribute17,Attribute19,Attribute20
521,-0.262292,-0.058908,-0.860109,-0.766124,-1.01353,-0.710931,-0.409736,A11,A32,A43,A61,A73,A92,A101,A121,A143,A152,A173,A191,A201
737,-0.262292,0.351952,0.031196,1.044509,-0.048994,-0.710931,2.440599,A11,A32,A40,A62,A73,A93,A101,A123,A143,A152,A172,A192,A201
740,0.24619,-0.357558,-0.860109,0.139192,-0.312049,-0.710931,-0.409736,A11,A31,A40,A62,A74,A93,A101,A123,A141,A152,A173,A191,A201
660,-0.770774,-0.712486,0.031196,1.044509,-1.101215,-0.710931,-0.409736,A13,A32,A43,A61,A73,A94,A101,A121,A143,A151,A173,A191,A201
411,1.008913,1.343886,0.031196,-0.766124,-0.048994,1.017777,-0.409736,A14,A34,A41,A61,A74,A93,A101,A123,A143,A152,A174,A192,A201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,0.24619,-0.043371,0.031196,-0.766124,-0.838159,-0.710931,-0.409736,A14,A32,A43,A63,A75,A91,A101,A123,A143,A152,A174,A192,A201
332,3.297082,1.397401,0.9225,-0.766124,-1.01353,-0.710931,-0.409736,A12,A32,A40,A62,A72,A92,A101,A122,A143,A152,A174,A191,A201
208,0.24619,1.107382,-0.860109,-0.766124,-1.276585,-0.710931,-0.409736,A11,A32,A49,A61,A73,A94,A101,A123,A142,A152,A172,A191,A201
613,0.24619,0.093697,-1.751413,1.044509,-1.1889,-0.710931,-0.409736,A11,A31,A41,A61,A73,A92,A103,A123,A141,A151,A173,A191,A202
78,2.7886,2.09759,-0.860109,-0.766124,0.301746,-0.710931,2.440599,A14,A30,A41,A65,A73,A93,A101,A122,A143,A152,A172,A191,A201

In [11]:
result1, runtime = prov.capture(X_test, X_test_scaled)
print_prov_result(X_test, X_test_scaled, result1)

Runtime: 0.0040 seconds

-- Record tensor --

<COOrdinate sparse matrix of dtype 'int8'
	with 200 stored elements and shape (200, 200)>
  Coords	Values
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1
  (4, 4)	1
  (5, 5)	1
  (6, 6)	1
  (7, 7)	1
  (8, 8)	1
  (9, 9)	1
  (10, 10)	1
  (11, 11)	1
  (12, 12)	1
  (13, 13)	1
  (14, 14)	1
  (15, 15)	1
  (16, 16)	1
  (17, 17)	1
  (18, 18)	1
  (19, 19)	1
  (20, 20)	1
  (21, 21)	1
  (22, 22)	1
  (23, 23)	1
  (24, 24)	1
  :	:
  (175, 175)	1
  (176, 176)	1
  (177, 177)	1
  (178, 178)	1
  (179, 179)	1
  (180, 180)	1
  (181, 181)	1
  (182, 182)	1
  (183, 183)	1
  (184, 184)	1
  (185, 185)	1
  (186, 186)	1
  (187, 187)	1
  (188, 188)	1
  (189, 189)	1
  (190, 190)	1
  (191, 191)	1
  (192, 192)	1
  (193, 193)	1
  (194, 194)	1
  (195, 195)	1
  (196, 196)	1
  (197, 197)	1
  (198, 198)	1
  (199, 199)	1

-- Record examples --

D_out[0] is from D_in[0]:
	    Attribute2 Attribute5 Attribute8 Attribute11 Attribute13 Attribute16  \
521  -0.262292  -0.058908  -0.860109   -0.766124    -1.01353   -0.710931

    Attribute18 Attribute1 Attribute3 Attribute4 Attribute6 Attribute7  \
521   -0.409736        A11        A32        A43        A61        A73

    Attribute9 Attribute10 Attribute12 Attribute14 Attribute15 Attribute17  \
521        A92        A101        A121        A143        A152        A173

    Attribute19 Attribute20
521        A191        A201
	is from
	    Attribute1  Attribute2 Attribute3 Attribute4  Attribute5 Attribute6  \
521        A11          18        A32        A43        3190        A61

    Attribute7  Attribute8 Attribute9 Attribute10  Attribute11 Attribute12  \
521        A73           2        A92        A101            2        A121

     Attribute13 Attribute14 Attribute15  Attribute16 Attribute17  \
521           24        A143        A152            1        A173

     Attribute18 Attribute19 Attribute20
521            1        A191        A201

D_out[1] is from D_in[1]:
	    Attribute2 Attribute5 Attribute8 Attribute11 Attribute13 Attribute16  \
737  -0.262292   0.351952   0.031196    1.044509   -0.048994   -0.710931

    Attribute18 Attribute1 Attribute3 Attribute4 Attribute6 Attribute7  \
737    2.440599        A11        A32        A40        A62        A73

    Attribute9 Attribute10 Attribute12 Attribute14 Attribute15 Attribute17  \
737        A93        A101        A123        A143        A152        A172

    Attribute19 Attribute20
737        A192        A201
	is from
	    Attribute1  Attribute2 Attribute3 Attribute4  Attribute5 Attribute6  \
737        A11          18        A32        A40        4380        A62

    Attribute7  Attribute8 Attribute9 Attribute10  Attribute11 Attribute12  \
737        A73           3        A93        A101            4        A123

     Attribute13 Attribute14 Attribute15  Attribute16 Attribute17  \
737           35        A143        A152            1        A172

     Attribute18 Attribute19 Attribute20
737            2        A192        A201

D_out[2] is from D_in[2]:
	    Attribute2 Attribute5 Attribute8 Attribute11 Attribute13 Attribute16  \
740    0.24619  -0.357558  -0.860109    0.139192   -0.312049   -0.710931

    Attribute18 Attribute1 Attribute3 Attribute4 Attribute6 Attribute7  \
740   -0.409736        A11        A31        A40        A62        A74

    Attribute9 Attribute10 Attribute12 Attribute14 Attribute15 Attribute17  \
740        A93        A101        A123        A141        A152        A173

    Attribute19 Attribute20
740        A191        A201
	is from
	    Attribute1  Attribute2 Attribute3 Attribute4  Attribute5 Attribute6  \
740        A11          24        A31        A40        2325        A62

    Attribute7  Attribute8 Attribute9 Attribute10  Attribute11 Attribute12  \
740        A74           2        A93        A101            3        A123

     Attribute13 Attribute14 Attribute15  Attribute16 Attribute17  \
740           32        A141        A152            1        A173

     Attribute18 Attribute19 Attribute20
740            1        A191        A201

D_out[3] is from D_in[3]:
	    Attribute2 Attribute5 Attribute8 Attribute11 Attribute13 Attribute16  \
660  -0.770774  -0.712486   0.031196    1.044509   -1.101215   -0.710931

    Attribute18 Attribute1 Attribute3 Attribute4 Attribute6 Attribute7  \
660   -0.409736        A13        A32        A43        A61        A73

    Attribute9 Attribute10 Attribute12 Attribute14 Attribute15 Attribute17  \
660        A94        A101        A121        A143        A151        A173

    Attribute19 Attribute20
660        A191        A201
	is from
	    Attribute1  Attribute2 Attribute3 Attribute4  Attribute5 Attribute6  \
660        A13          12        A32        A43        1297        A61

    Attribute7  Attribute8 Attribute9 Attribute10  Attribute11 Attribute12  \
660        A73           3        A94        A101            4        A121

     Attribute13 Attribute14 Attribute15  Attribute16 Attribute17  \
660           23        A143        A151            1        A173

     Attribute18 Attribute19 Attribute20
660            1        A191        A201

D_out[4] is from D_in[4]:
	    Attribute2 Attribute5 Attribute8 Attribute11 Attribute13 Attribute16  \
411   1.008913   1.343886   0.031196   -0.766124   -0.048994    1.017777

    Attribute18 Attribute1 Attribute3 Attribute4 Attribute6 Attribute7  \
411   -0.409736        A14        A34        A41        A61        A74

    Attribute9 Attribute10 Attribute12 Attribute14 Attribute15 Attribute17  \
411        A93        A101        A123        A143        A152        A174

    Attribute19 Attribute20
411        A192        A201
	is from
	    Attribute1  Attribute2 Attribute3 Attribute4  Attribute5 Attribute6  \
411        A14          33        A34        A41        7253        A61

    Attribute7  Attribute8 Attribute9 Attribute10  Attribute11 Attribute12  \
411        A74           3        A93        A101            2        A123

     Attribute13 Attribute14 Attribute15  Attribute16 Attribute17  \
411           35        A143        A152            2        A174

     Attribute18 Attribute19 Attribute20
411            1        A192        A201

... 200 items in total.

-- Attr tensor --

<COOrdinate sparse matrix of dtype 'int8'
	with 20 stored elements and shape (20, 20)>
  Coords	Values
  (0, 1)	1
  (1, 4)	1
  (2, 7)	1
  (3, 10)	1
  (4, 12)	1
  (5, 15)	1
  (6, 17)	1
  (7, 0)	1
  (8, 2)	1
  (9, 3)	1
  (10, 5)	1
  (11, 6)	1
  (12, 8)	1
  (13, 9)	1
  (14, 11)	1
  (15, 13)	1
  (16, 14)	1
  (17, 16)	1
  (18, 18)	1
  (19, 19)	1

-- Attr examples --

D_out[Attribute2] is from D_in[Attribute2]
D_out[Attribute5] is from D_in[Attribute5]
D_out[Attribute8] is from D_in[Attribute8]
D_out[Attribute11] is from D_in[Attribute11]
D_out[Attribute13] is from D_in[Attribute13]
D_out[Attribute16] is from D_in[Attribute16]
D_out[Attribute18] is from D_in[Attribute18]
D_out[Attribute1] is from D_in[Attribute1]
D_out[Attribute3] is from D_in[Attribute3]
D_out[Attribute4] is from D_in[Attribute4]
D_out[Attribute6] is from D_in[Attribute6]
D_out[Attribute7] is from D_in[Attribute7]
D_out[Attribute9] is from D_in[Attribute9]
D_out[Attribute10] is from D_in[Attribute10]
D_out[Attribute12] is from D_in[Attribute12]
D_out[Attribute14] is from D_in[Attribute14]
D_out[Attribute15] is from D_in[Attribute15]
D_out[Attribute17] is from D_in[Attribute17]
D_out[Attribute19] is from D_in[Attribute19]
D_out[Attribute20] is from D_in[Attribute20]

# 2. Vertical Augmentation

One-Hot Encoding for categorical features.

In [12]:
# Inject an error
i_alice = 3
X_test_scaled.iloc[i_alice, 7] = "A11"
X_test_scaled

,Attribute2,Attribute5,Attribute8,Attribute11,Attribute13,Attribute16,Attribute18,Attribute1,Attribute3,Attribute4,Attribute6,Attribute7,Attribute9,Attribute10,Attribute12,Attribute14,Attribute15,Attribute17,Attribute19,Attribute20
521,-0.262292,-0.058908,-0.860109,-0.766124,-1.01353,-0.710931,-0.409736,A11,A32,A43,A61,A73,A92,A101,A121,A143,A152,A173,A191,A201
737,-0.262292,0.351952,0.031196,1.044509,-0.048994,-0.710931,2.440599,A11,A32,A40,A62,A73,A93,A101,A123,A143,A152,A172,A192,A201
740,0.24619,-0.357558,-0.860109,0.139192,-0.312049,-0.710931,-0.409736,A11,A31,A40,A62,A74,A93,A101,A123,A141,A152,A173,A191,A201
660,-0.770774,-0.712486,0.031196,1.044509,-1.101215,-0.710931,-0.409736,A11,A32,A43,A61,A73,A94,A101,A121,A143,A151,A173,A191,A201
411,1.008913,1.343886,0.031196,-0.766124,-0.048994,1.017777,-0.409736,A14,A34,A41,A61,A74,A93,A101,A123,A143,A152,A174,A192,A201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,0.24619,-0.043371,0.031196,-0.766124,-0.838159,-0.710931,-0.409736,A14,A32,A43,A63,A75,A91,A101,A123,A143,A152,A174,A192,A201
332,3.297082,1.397401,0.9225,-0.766124,-1.01353,-0.710931,-0.409736,A12,A32,A40,A62,A72,A92,A101,A122,A143,A152,A174,A191,A201
208,0.24619,1.107382,-0.860109,-0.766124,-1.276585,-0.710931,-0.409736,A11,A32,A49,A61,A73,A94,A101,A123,A142,A152,A172,A191,A201
613,0.24619,0.093697,-1.751413,1.044509,-1.1889,-0.710931,-0.409736,A11,A31,A41,A61,A73,A92,A103,A123,A141,A151,A173,A191,A202
78,2.7886,2.09759,-0.860109,-0.766124,0.301746,-0.710931,2.440599,A14,A30,A41,A65,A73,A93,A101,A122,A143,A152,A172,A191,A201

In [13]:
encoder = model.named_steps['preprocessor'].named_transformers_['cat'].named_steps['encoder']
X_test_categorical_encoded = encoder.transform(X_test_scaled[categorical_features])
# Convert back to DataFrame
encoded_features = encoder.get_feature_names_out()
X_test_encoded = pd.DataFrame(
    np.hstack([X_test_numerical_scaled, X_test_categorical_encoded]),
    columns=numerical_features + list(encoded_features),
    index=X_test.index
)
X_test_encoded

,Attribute2,Attribute5,Attribute8,Attribute11,Attribute13,Attribute16,Attribute18,Attribute1_A11,Attribute1_A12,Attribute1_A13,...,Attribute15_A152,Attribute15_A153,Attribute17_A171,Attribute17_A172,Attribute17_A173,Attribute17_A174,Attribute19_A191,Attribute19_A192,Attribute20_A201,Attribute20_A202
521,-0.262292,-0.058908,-0.860109,-0.766124,-1.013530,-0.710931,-0.409736,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
737,-0.262292,0.351952,0.031196,1.044509,-0.048994,-0.710931,2.440599,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
740,0.246190,-0.357558,-0.860109,0.139192,-0.312049,-0.710931,-0.409736,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
660,-0.770774,-0.712486,0.031196,1.044509,-1.101215,-0.710931,-0.409736,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
411,1.008913,1.343886,0.031196,-0.766124,-0.048994,1.017777,-0.409736,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,0.246190,-0.043371,0.031196,-0.766124,-0.838159,-0.710931,-0.409736,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
332,3.297082,1.397401,0.922500,-0.766124,-1.013530,-0.710931,-0.409736,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
208,0.246190,1.107382,-0.860109,-0.766124,-1.276585,-0.710931,-0.409736,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
613,0.246190,0.093697,-1.751413,1.044509,-1.188900,-0.710931,-0.409736,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
78,2.788600,2.097590,-0.860109,-0.766124,0.301746,-0.710931,2.440599,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

# Provenance

In [14]:
def get_onehot_mapping(encoder):
    mapping = {}
    for col_in, cats in zip(encoder.feature_names_in_, encoder.categories_):
        mapping[col_in] = [f"{col_in}_{cat}" for cat in cats]
    return mapping

mapping = get_onehot_mapping(encoder)
result2, runtime = prov.capture(X_test_scaled, X_test_encoded, column_mapping=mapping)
print_prov_result(X_test_scaled, X_test_encoded, result2)

Runtime: 0.0009 seconds

-- Record tensor --

<COOrdinate sparse matrix of dtype 'int8'
	with 200 stored elements and shape (200, 200)>
  Coords	Values
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1
  (4, 4)	1
  (5, 5)	1
  (6, 6)	1
  (7, 7)	1
  (8, 8)	1
  (9, 9)	1
  (10, 10)	1
  (11, 11)	1
  (12, 12)	1
  (13, 13)	1
  (14, 14)	1
  (15, 15)	1
  (16, 16)	1
  (17, 17)	1
  (18, 18)	1
  (19, 19)	1
  (20, 20)	1
  (21, 21)	1
  (22, 22)	1
  (23, 23)	1
  (24, 24)	1
  :	:
  (175, 175)	1
  (176, 176)	1
  (177, 177)	1
  (178, 178)	1
  (179, 179)	1
  (180, 180)	1
  (181, 181)	1
  (182, 182)	1
  (183, 183)	1
  (184, 184)	1
  (185, 185)	1
  (186, 186)	1
  (187, 187)	1
  (188, 188)	1
  (189, 189)	1
  (190, 190)	1
  (191, 191)	1
  (192, 192)	1
  (193, 193)	1
  (194, 194)	1
  (195, 195)	1
  (196, 196)	1
  (197, 197)	1
  (198, 198)	1
  (199, 199)	1

-- Record examples --

D_out[0] is from D_in[0]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
521   -0.262292   -0.058908   -0.860109    -0.766124     -1.01353

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
521    -0.710931    -0.409736             1.0             0.0             0.0

     ...  Attribute15_A152  Attribute15_A153  Attribute17_A171  \
521  ...               1.0               0.0               0.0

     Attribute17_A172  Attribute17_A173  Attribute17_A174  Attribute19_A191  \
521               0.0               1.0               0.0               1.0

     Attribute19_A192  Attribute20_A201  Attribute20_A202
521               0.0               1.0               0.0

[1 rows x 61 columns]
	is from
	    Attribute2 Attribute5 Attribute8 Attribute11 Attribute13 Attribute16  \
521  -0.262292  -0.058908  -0.860109   -0.766124    -1.01353   -0.710931

    Attribute18 Attribute1 Attribute3 Attribute4 Attribute6 Attribute7  \
521   -0.409736        A11        A32        A43        A61        A73

    Attribute9 Attribute10 Attribute12 Attribute14 Attribute15 Attribute17  \
521        A92        A101        A121        A143        A152        A173

    Attribute19 Attribute20
521        A191        A201

D_out[1] is from D_in[1]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
737   -0.262292    0.351952    0.031196     1.044509    -0.048994

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
737    -0.710931     2.440599             1.0             0.0             0.0

     ...  Attribute15_A152  Attribute15_A153  Attribute17_A171  \
737  ...               1.0               0.0               0.0

     Attribute17_A172  Attribute17_A173  Attribute17_A174  Attribute19_A191  \
737               1.0               0.0               0.0               0.0

     Attribute19_A192  Attribute20_A201  Attribute20_A202
737               1.0               1.0               0.0

[1 rows x 61 columns]
	is from
	    Attribute2 Attribute5 Attribute8 Attribute11 Attribute13 Attribute16  \
737  -0.262292   0.351952   0.031196    1.044509   -0.048994   -0.710931

    Attribute18 Attribute1 Attribute3 Attribute4 Attribute6 Attribute7  \
737    2.440599        A11        A32        A40        A62        A73

    Attribute9 Attribute10 Attribute12 Attribute14 Attribute15 Attribute17  \
737        A93        A101        A123        A143        A152        A172

    Attribute19 Attribute20
737        A192        A201

D_out[2] is from D_in[2]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
740     0.24619   -0.357558   -0.860109     0.139192    -0.312049

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
740    -0.710931    -0.409736             1.0             0.0             0.0

     ...  Attribute15_A152  Attribute15_A153  Attribute17_A171  \
740  ...               1.0               0.0               0.0

     Attribute17_A172  Attribute17_A173  Attribute17_A174  Attribute19_A191  \
740               0.0               1.0               0.0               1.0

     Attribute19_A192  Attribute20_A201  Attribute20_A202
740               0.0               1.0               0.0

[1 rows x 61 columns]
	is from
	    Attribute2 Attribute5 Attribute8 Attribute11 Attribute13 Attribute16  \
740    0.24619  -0.357558  -0.860109    0.139192   -0.312049   -0.710931

    Attribute18 Attribute1 Attribute3 Attribute4 Attribute6 Attribute7  \
740   -0.409736        A11        A31        A40        A62        A74

    Attribute9 Attribute10 Attribute12 Attribute14 Attribute15 Attribute17  \
740        A93        A101        A123        A141        A152        A173

    Attribute19 Attribute20
740        A191        A201

D_out[3] is from D_in[3]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
660   -0.770774   -0.712486    0.031196     1.044509    -1.101215

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
660    -0.710931    -0.409736             1.0             0.0             0.0

     ...  Attribute15_A152  Attribute15_A153  Attribute17_A171  \
660  ...               0.0               0.0               0.0

     Attribute17_A172  Attribute17_A173  Attribute17_A174  Attribute19_A191  \
660               0.0               1.0               0.0               1.0

     Attribute19_A192  Attribute20_A201  Attribute20_A202
660               0.0               1.0               0.0

[1 rows x 61 columns]
	is from
	    Attribute2 Attribute5 Attribute8 Attribute11 Attribute13 Attribute16  \
660  -0.770774  -0.712486   0.031196    1.044509   -1.101215   -0.710931

    Attribute18 Attribute1 Attribute3 Attribute4 Attribute6 Attribute7  \
660   -0.409736        A11        A32        A43        A61        A73

    Attribute9 Attribute10 Attribute12 Attribute14 Attribute15 Attribute17  \
660        A94        A101        A121        A143        A151        A173

    Attribute19 Attribute20
660        A191        A201

D_out[4] is from D_in[4]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
411    1.008913    1.343886    0.031196    -0.766124    -0.048994

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
411     1.017777    -0.409736             0.0             0.0             0.0

     ...  Attribute15_A152  Attribute15_A153  Attribute17_A171  \
411  ...               1.0               0.0               0.0

     Attribute17_A172  Attribute17_A173  Attribute17_A174  Attribute19_A191  \
411               0.0               0.0               1.0               0.0

     Attribute19_A192  Attribute20_A201  Attribute20_A202
411               1.0               1.0               0.0

[1 rows x 61 columns]
	is from
	    Attribute2 Attribute5 Attribute8 Attribute11 Attribute13 Attribute16  \
411   1.008913   1.343886   0.031196   -0.766124   -0.048994    1.017777

    Attribute18 Attribute1 Attribute3 Attribute4 Attribute6 Attribute7  \
411   -0.409736        A14        A34        A41        A61        A74

    Attribute9 Attribute10 Attribute12 Attribute14 Attribute15 Attribute17  \
411        A93        A101        A123        A143        A152        A174

    Attribute19 Attribute20
411        A192        A201

... 200 items in total.

-- Attr tensor --

<COOrdinate sparse matrix of dtype 'int8'
	with 61 stored elements and shape (61, 20)>
  Coords	Values
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1
  (4, 4)	1
  (5, 5)	1
  (6, 6)	1
  (7, 7)	1
  (8, 7)	1
  (9, 7)	1
  (10, 7)	1
  (11, 8)	1
  (12, 8)	1
  (13, 8)	1
  (14, 8)	1
  (15, 8)	1
  (16, 9)	1
  (17, 9)	1
  (18, 9)	1
  (19, 9)	1
  (20, 9)	1
  (21, 9)	1
  (22, 9)	1
  (23, 9)	1
  (24, 9)	1
  :	:
  (36, 12)	1
  (37, 12)	1
  (38, 12)	1
  (39, 12)	1
  (40, 13)	1
  (41, 13)	1
  (42, 13)	1
  (43, 14)	1
  (44, 14)	1
  (45, 14)	1
  (46, 14)	1
  (47, 15)	1
  (48, 15)	1
  (49, 15)	1
  (50, 16)	1
  (51, 16)	1
  (52, 16)	1
  (53, 17)	1
  (54, 17)	1
  (55, 17)	1
  (56, 17)	1
  (57, 18)	1
  (58, 18)	1
  (59, 19)	1
  (60, 19)	1

-- Attr examples --

D_out[Attribute2] is from D_in[Attribute2]
D_out[Attribute5] is from D_in[Attribute5]
D_out[Attribute8] is from D_in[Attribute8]
D_out[Attribute11] is from D_in[Attribute11]
D_out[Attribute13] is from D_in[Attribute13]
D_out[Attribute16] is from D_in[Attribute16]
D_out[Attribute18] is from D_in[Attribute18]
D_out[Attribute1_A11] is from D_in[Attribute1]
D_out[Attribute1_A12] is from D_in[Attribute1]
D_out[Attribute1_A13] is from D_in[Attribute1]
D_out[Attribute1_A14] is from D_in[Attribute1]
D_out[Attribute3_A30] is from D_in[Attribute3]
D_out[Attribute3_A31] is from D_in[Attribute3]
D_out[Attribute3_A32] is from D_in[Attribute3]
D_out[Attribute3_A33] is from D_in[Attribute3]
D_out[Attribute3_A34] is from D_in[Attribute3]
D_out[Attribute4_A40] is from D_in[Attribute4]
D_out[Attribute4_A41] is from D_in[Attribute4]
D_out[Attribute4_A410] is from D_in[Attribute4]
D_out[Attribute4_A42] is from D_in[Attribute4]
D_out[Attribute4_A43] is from D_in[Attribute4]
D_out[Attribute4_A44] is from D_in[Attribute4]
D_out[Attribute4_A45] is from D_in[Attribute4]
D_out[Attribute4_A46] is from D_in[Attribute4]
D_out[Attribute4_A48] is from D_in[Attribute4]
D_out[Attribute4_A49] is from D_in[Attribute4]
D_out[Attribute6_A61] is from D_in[Attribute6]
D_out[Attribute6_A62] is from D_in[Attribute6]
D_out[Attribute6_A63] is from D_in[Attribute6]
D_out[Attribute6_A64] is from D_in[Attribute6]
D_out[Attribute6_A65] is from D_in[Attribute6]
D_out[Attribute7_A71] is from D_in[Attribute7]
D_out[Attribute7_A72] is from D_in[Attribute7]
D_out[Attribute7_A73] is from D_in[Attribute7]
D_out[Attribute7_A74] is from D_in[Attribute7]
D_out[Attribute7_A75] is from D_in[Attribute7]
D_out[Attribute9_A91] is from D_in[Attribute9]
D_out[Attribute9_A92] is from D_in[Attribute9]
D_out[Attribute9_A93] is from D_in[Attribute9]
D_out[Attribute9_A94] is from D_in[Attribute9]
D_out[Attribute10_A101] is from D_in[Attribute10]
D_out[Attribute10_A102] is from D_in[Attribute10]
D_out[Attribute10_A103] is from D_in[Attribute10]
D_out[Attribute12_A121] is from D_in[Attribute12]
D_out[Attribute12_A122] is from D_in[Attribute12]
D_out[Attribute12_A123] is from D_in[Attribute12]
D_out[Attribute12_A124] is from D_in[Attribute12]
D_out[Attribute14_A141] is from D_in[Attribute14]
D_out[Attribute14_A142] is from D_in[Attribute14]
D_out[Attribute14_A143] is from D_in[Attribute14]
D_out[Attribute15_A151] is from D_in[Attribute15]
D_out[Attribute15_A152] is from D_in[Attribute15]
D_out[Attribute15_A153] is from D_in[Attribute15]
D_out[Attribute17_A171] is from D_in[Attribute17]
D_out[Attribute17_A172] is from D_in[Attribute17]
D_out[Attribute17_A173] is from D_in[Attribute17]
D_out[Attribute17_A174] is from D_in[Attribute17]
D_out[Attribute19_A191] is from D_in[Attribute19]
D_out[Attribute19_A192] is from D_in[Attribute19]
D_out[Attribute20_A201] is from D_in[Attribute20]
D_out[Attribute20_A202] is from D_in[Attribute20]

# 3.Vertical Reduction

Select features by Chi-Square.  
Features with p-values <= 0.05 are considered statistically significant, indicating that they are likely associated with the target variable rather than occurring by chance.

In [15]:
selector = model.named_steps['preprocessor'].named_transformers_['cat'].named_steps['selector']
X_test_categorical_selected = selector.transform(X_test_encoded[encoded_features].to_numpy())
# Convert back to DataFrame
selected_features = pd.Index(encoded_features)[selector.get_support()].to_list()
X_test_selected = pd.DataFrame(
    np.hstack([X_test_numerical_scaled, X_test_categorical_selected]),
    columns=numerical_features + selected_features,
    index=X_test.index
)
X_test_selected

,Attribute2,Attribute5,Attribute8,Attribute11,Attribute13,Attribute16,Attribute18,Attribute1_A11,Attribute1_A12,Attribute1_A13,...,Attribute12_A124,Attribute14_A141,Attribute14_A142,Attribute14_A143,Attribute15_A151,Attribute15_A152,Attribute15_A153,Attribute17_A172,Attribute17_A174,Attribute20_A202
521,-0.262292,-0.058908,-0.860109,-0.766124,-1.013530,-0.710931,-0.409736,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
737,-0.262292,0.351952,0.031196,1.044509,-0.048994,-0.710931,2.440599,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
740,0.246190,-0.357558,-0.860109,0.139192,-0.312049,-0.710931,-0.409736,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
660,-0.770774,-0.712486,0.031196,1.044509,-1.101215,-0.710931,-0.409736,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
411,1.008913,1.343886,0.031196,-0.766124,-0.048994,1.017777,-0.409736,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,0.246190,-0.043371,0.031196,-0.766124,-0.838159,-0.710931,-0.409736,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
332,3.297082,1.397401,0.922500,-0.766124,-1.013530,-0.710931,-0.409736,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
208,0.246190,1.107382,-0.860109,-0.766124,-1.276585,-0.710931,-0.409736,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
613,0.246190,0.093697,-1.751413,1.044509,-1.188900,-0.710931,-0.409736,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
78,2.788600,2.097590,-0.860109,-0.766124,0.301746,-0.710931,2.440599,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0

In [16]:
result3, runtime = prov.capture(X_test_encoded, X_test_selected)
print_prov_result(X_test_encoded, X_test_selected, result3)

Runtime: 0.0004 seconds

-- Record tensor --

<COOrdinate sparse matrix of dtype 'int8'
	with 200 stored elements and shape (200, 200)>
  Coords	Values
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1
  (4, 4)	1
  (5, 5)	1
  (6, 6)	1
  (7, 7)	1
  (8, 8)	1
  (9, 9)	1
  (10, 10)	1
  (11, 11)	1
  (12, 12)	1
  (13, 13)	1
  (14, 14)	1
  (15, 15)	1
  (16, 16)	1
  (17, 17)	1
  (18, 18)	1
  (19, 19)	1
  (20, 20)	1
  (21, 21)	1
  (22, 22)	1
  (23, 23)	1
  (24, 24)	1
  :	:
  (175, 175)	1
  (176, 176)	1
  (177, 177)	1
  (178, 178)	1
  (179, 179)	1
  (180, 180)	1
  (181, 181)	1
  (182, 182)	1
  (183, 183)	1
  (184, 184)	1
  (185, 185)	1
  (186, 186)	1
  (187, 187)	1
  (188, 188)	1
  (189, 189)	1
  (190, 190)	1
  (191, 191)	1
  (192, 192)	1
  (193, 193)	1
  (194, 194)	1
  (195, 195)	1
  (196, 196)	1
  (197, 197)	1
  (198, 198)	1
  (199, 199)	1

-- Record examples --

D_out[0] is from D_in[0]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
521   -0.262292   -0.058908   -0.860109    -0.766124     -1.01353

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
521    -0.710931    -0.409736             1.0             0.0             0.0

     ...  Attribute12_A124  Attribute14_A141  Attribute14_A142  \
521  ...               0.0               0.0               0.0

     Attribute14_A143  Attribute15_A151  Attribute15_A152  Attribute15_A153  \
521               1.0               0.0               1.0               0.0

     Attribute17_A172  Attribute17_A174  Attribute20_A202
521               0.0               0.0               0.0

[1 rows x 47 columns]
	is from
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
521   -0.262292   -0.058908   -0.860109    -0.766124     -1.01353

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
521    -0.710931    -0.409736             1.0             0.0             0.0

     ...  Attribute15_A152  Attribute15_A153  Attribute17_A171  \
521  ...               1.0               0.0               0.0

     Attribute17_A172  Attribute17_A173  Attribute17_A174  Attribute19_A191  \
521               0.0               1.0               0.0               1.0

     Attribute19_A192  Attribute20_A201  Attribute20_A202
521               0.0               1.0               0.0

[1 rows x 61 columns]

D_out[1] is from D_in[1]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
737   -0.262292    0.351952    0.031196     1.044509    -0.048994

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
737    -0.710931     2.440599             1.0             0.0             0.0

     ...  Attribute12_A124  Attribute14_A141  Attribute14_A142  \
737  ...               0.0               0.0               0.0

     Attribute14_A143  Attribute15_A151  Attribute15_A152  Attribute15_A153  \
737               1.0               0.0               1.0               0.0

     Attribute17_A172  Attribute17_A174  Attribute20_A202
737               1.0               0.0               0.0

[1 rows x 47 columns]
	is from
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
737   -0.262292    0.351952    0.031196     1.044509    -0.048994

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
737    -0.710931     2.440599             1.0             0.0             0.0

     ...  Attribute15_A152  Attribute15_A153  Attribute17_A171  \
737  ...               1.0               0.0               0.0

     Attribute17_A172  Attribute17_A173  Attribute17_A174  Attribute19_A191  \
737               1.0               0.0               0.0               0.0

     Attribute19_A192  Attribute20_A201  Attribute20_A202
737               1.0               1.0               0.0

[1 rows x 61 columns]

D_out[2] is from D_in[2]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
740     0.24619   -0.357558   -0.860109     0.139192    -0.312049

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
740    -0.710931    -0.409736             1.0             0.0             0.0

     ...  Attribute12_A124  Attribute14_A141  Attribute14_A142  \
740  ...               0.0               1.0               0.0

     Attribute14_A143  Attribute15_A151  Attribute15_A152  Attribute15_A153  \
740               0.0               0.0               1.0               0.0

     Attribute17_A172  Attribute17_A174  Attribute20_A202
740               0.0               0.0               0.0

[1 rows x 47 columns]
	is from
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
740     0.24619   -0.357558   -0.860109     0.139192    -0.312049

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
740    -0.710931    -0.409736             1.0             0.0             0.0

     ...  Attribute15_A152  Attribute15_A153  Attribute17_A171  \
740  ...               1.0               0.0               0.0

     Attribute17_A172  Attribute17_A173  Attribute17_A174  Attribute19_A191  \
740               0.0               1.0               0.0               1.0

     Attribute19_A192  Attribute20_A201  Attribute20_A202
740               0.0               1.0               0.0

[1 rows x 61 columns]

D_out[3] is from D_in[3]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
660   -0.770774   -0.712486    0.031196     1.044509    -1.101215

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
660    -0.710931    -0.409736             1.0             0.0             0.0

     ...  Attribute12_A124  Attribute14_A141  Attribute14_A142  \
660  ...               0.0               0.0               0.0

     Attribute14_A143  Attribute15_A151  Attribute15_A152  Attribute15_A153  \
660               1.0               1.0               0.0               0.0

     Attribute17_A172  Attribute17_A174  Attribute20_A202
660               0.0               0.0               0.0

[1 rows x 47 columns]
	is from
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
660   -0.770774   -0.712486    0.031196     1.044509    -1.101215

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
660    -0.710931    -0.409736             1.0             0.0             0.0

     ...  Attribute15_A152  Attribute15_A153  Attribute17_A171  \
660  ...               0.0               0.0               0.0

     Attribute17_A172  Attribute17_A173  Attribute17_A174  Attribute19_A191  \
660               0.0               1.0               0.0               1.0

     Attribute19_A192  Attribute20_A201  Attribute20_A202
660               0.0               1.0               0.0

[1 rows x 61 columns]

D_out[4] is from D_in[4]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
411    1.008913    1.343886    0.031196    -0.766124    -0.048994

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
411     1.017777    -0.409736             0.0             0.0             0.0

     ...  Attribute12_A124  Attribute14_A141  Attribute14_A142  \
411  ...               0.0               0.0               0.0

     Attribute14_A143  Attribute15_A151  Attribute15_A152  Attribute15_A153  \
411               1.0               0.0               1.0               0.0

     Attribute17_A172  Attribute17_A174  Attribute20_A202
411               0.0               1.0               0.0

[1 rows x 47 columns]
	is from
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
411    1.008913    1.343886    0.031196    -0.766124    -0.048994

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
411     1.017777    -0.409736             0.0             0.0             0.0

     ...  Attribute15_A152  Attribute15_A153  Attribute17_A171  \
411  ...               1.0               0.0               0.0

     Attribute17_A172  Attribute17_A173  Attribute17_A174  Attribute19_A191  \
411               0.0               0.0               1.0               0.0

     Attribute19_A192  Attribute20_A201  Attribute20_A202
411               1.0               1.0               0.0

[1 rows x 61 columns]

... 200 items in total.

-- Attr tensor --

<COOrdinate sparse matrix of dtype 'int8'
	with 47 stored elements and shape (47, 61)>
  Coords	Values
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1
  (4, 4)	1
  (5, 5)	1
  (6, 6)	1
  (7, 7)	1
  (8, 8)	1
  (9, 9)	1
  (10, 10)	1
  (11, 11)	1
  (12, 12)	1
  (13, 13)	1
  (14, 15)	1
  (15, 16)	1
  (16, 17)	1
  (17, 18)	1
  (18, 20)	1
  (19, 23)	1
  (20, 24)	1
  (21, 25)	1
  (22, 26)	1
  (23, 27)	1
  (24, 28)	1
  (25, 29)	1
  (26, 30)	1
  (27, 31)	1
  (28, 32)	1
  (29, 34)	1
  (30, 35)	1
  (31, 36)	1
  (32, 37)	1
  (33, 38)	1
  (34, 42)	1
  (35, 43)	1
  (36, 45)	1
  (37, 46)	1
  (38, 47)	1
  (39, 48)	1
  (40, 49)	1
  (41, 50)	1
  (42, 51)	1
  (43, 52)	1
  (44, 54)	1
  (45, 56)	1
  (46, 60)	1

-- Attr examples --

D_out[Attribute2] is from D_in[Attribute2]
D_out[Attribute5] is from D_in[Attribute5]
D_out[Attribute8] is from D_in[Attribute8]
D_out[Attribute11] is from D_in[Attribute11]
D_out[Attribute13] is from D_in[Attribute13]
D_out[Attribute16] is from D_in[Attribute16]
D_out[Attribute18] is from D_in[Attribute18]
D_out[Attribute1_A11] is from D_in[Attribute1_A11]
D_out[Attribute1_A12] is from D_in[Attribute1_A12]
D_out[Attribute1_A13] is from D_in[Attribute1_A13]
D_out[Attribute1_A14] is from D_in[Attribute1_A14]
D_out[Attribute3_A30] is from D_in[Attribute3_A30]
D_out[Attribute3_A31] is from D_in[Attribute3_A31]
D_out[Attribute3_A32] is from D_in[Attribute3_A32]
D_out[Attribute3_A34] is from D_in[Attribute3_A34]
D_out[Attribute4_A40] is from D_in[Attribute4_A40]
D_out[Attribute4_A41] is from D_in[Attribute4_A41]
D_out[Attribute4_A410] is from D_in[Attribute4_A410]
D_out[Attribute4_A43] is from D_in[Attribute4_A43]
D_out[Attribute4_A46] is from D_in[Attribute4_A46]
D_out[Attribute4_A48] is from D_in[Attribute4_A48]
D_out[Attribute4_A49] is from D_in[Attribute4_A49]
D_out[Attribute6_A61] is from D_in[Attribute6_A61]
D_out[Attribute6_A62] is from D_in[Attribute6_A62]
D_out[Attribute6_A63] is from D_in[Attribute6_A63]
D_out[Attribute6_A64] is from D_in[Attribute6_A64]
D_out[Attribute6_A65] is from D_in[Attribute6_A65]
D_out[Attribute7_A71] is from D_in[Attribute7_A71]
D_out[Attribute7_A72] is from D_in[Attribute7_A72]
D_out[Attribute7_A74] is from D_in[Attribute7_A74]
D_out[Attribute7_A75] is from D_in[Attribute7_A75]
D_out[Attribute9_A91] is from D_in[Attribute9_A91]
D_out[Attribute9_A92] is from D_in[Attribute9_A92]
D_out[Attribute9_A93] is from D_in[Attribute9_A93]
D_out[Attribute10_A103] is from D_in[Attribute10_A103]
D_out[Attribute12_A121] is from D_in[Attribute12_A121]
D_out[Attribute12_A123] is from D_in[Attribute12_A123]
D_out[Attribute12_A124] is from D_in[Attribute12_A124]
D_out[Attribute14_A141] is from D_in[Attribute14_A141]
D_out[Attribute14_A142] is from D_in[Attribute14_A142]
D_out[Attribute14_A143] is from D_in[Attribute14_A143]
D_out[Attribute15_A151] is from D_in[Attribute15_A151]
D_out[Attribute15_A152] is from D_in[Attribute15_A152]
D_out[Attribute15_A153] is from D_in[Attribute15_A153]
D_out[Attribute17_A172] is from D_in[Attribute17_A172]
D_out[Attribute17_A174] is from D_in[Attribute17_A174]
D_out[Attribute20_A202] is from D_in[Attribute20_A202]

# Evaluation

In [17]:
from sklearn.metrics import classification_report

classifier = model.named_steps['classifier']
y_test_pred = classifier.predict(X_test_selected)
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           1       0.86      0.92      0.89       141
           2       0.77      0.63      0.69        59

    accuracy                           0.83       200
   macro avg       0.81      0.77      0.79       200
weighted avg       0.83      0.83      0.83       200

C:\Users\30315\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [18]:
y_test.iloc[i_alice]["class"]

np.int64(1)

In [19]:
y_test_pred[3]

np.int64(2)

# Debugging

Alice has a good credit history but was denied a loan.   
It is due to an encoding error of Attribute1 (Status of existing checking account),   
A13 (>= 200 DM / salary assignments for at least 1 year)
was mistakenly encoded as 
A11 (< 0 DM).

In [20]:
dfs = [X_test, X_test_scaled, X_test_encoded, X_test_selected]
results = [result1, result2, result3]
tensors_record = [result[0] for result in results]
tensors_attr = [result[1] for result in results]

trace_record = trace(tensors_record, direction="backward", indices=[i_alice])
# trace_record = trace(tensors_record, direction="backward", indices=[i_alice], keep_path=True)
tensors_attr = trace(tensors_attr, direction="backward")
print_prov_result(X_test, X_test_selected, (trace_record, tensors_attr))

# print(trace_record)
# print(tensors_attr)

-- Record tensor --

[[3 3]]

-- Record examples --

D_out[3] is from D_in[3]:
	     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
660   -0.770774   -0.712486    0.031196     1.044509    -1.101215

     Attribute16  Attribute18  Attribute1_A11  Attribute1_A12  Attribute1_A13  \
660    -0.710931    -0.409736             1.0             0.0             0.0

     ...  Attribute12_A124  Attribute14_A141  Attribute14_A142  \
660  ...               0.0               0.0               0.0

     Attribute14_A143  Attribute15_A151  Attribute15_A152  Attribute15_A153  \
660               1.0               1.0               0.0               0.0

     Attribute17_A172  Attribute17_A174  Attribute20_A202
660               0.0               0.0               0.0

[1 rows x 47 columns]
	is from
	    Attribute1  Attribute2 Attribute3 Attribute4  Attribute5 Attribute6  \
660        A13          12        A32        A43        1297        A61

    Attribute7  Attribute8 Attribute9 Attribute10  Attribute11 Attribute12  \
660        A73           3        A94        A101            4        A121

     Attribute13 Attribute14 Attribute15  Attribute16 Attribute17  \
660           23        A143        A151            1        A173

     Attribute18 Attribute19 Attribute20
660            1        A191        A201


-- Attr tensor --

[[ 0  1]
 [ 1  4]
 [ 2  7]
 [ 3 10]
 [ 4 12]
 [ 5 15]
 [ 6 17]
 [ 7  0]
 [ 8  0]
 [ 9  0]
 [10  0]
 [11  2]
 [12  2]
 [13  2]
 [14  2]
 [15  3]
 [16  3]
 [17  3]
 [18  3]
 [19  3]
 [20  3]
 [21  3]
 [22  5]
 [23  5]
 [24  5]
 [25  5]
 [26  5]
 [27  6]
 [28  6]
 [29  6]
 [30  6]
 [31  8]
 [32  8]
 [33  8]
 [34  9]
 [35 11]
 [36 11]
 [37 11]
 [38 13]
 [39 13]
 [40 13]
 [41 14]
 [42 14]
 [43 14]
 [44 16]
 [45 16]
 [46 19]]

-- Attr examples --

D_out[Attribute2] is from D_in[Attribute2]
D_out[Attribute5] is from D_in[Attribute5]
D_out[Attribute8] is from D_in[Attribute8]
D_out[Attribute11] is from D_in[Attribute11]
D_out[Attribute13] is from D_in[Attribute13]
D_out[Attribute16] is from D_in[Attribute16]
D_out[Attribute18] is from D_in[Attribute18]
D_out[Attribute1_A11] is from D_in[Attribute1]
D_out[Attribute1_A12] is from D_in[Attribute1]
D_out[Attribute1_A13] is from D_in[Attribute1]
D_out[Attribute1_A14] is from D_in[Attribute1]
D_out[Attribute3_A30] is from D_in[Attribute3]
D_out[Attribute3_A31] is from D_in[Attribute3]
D_out[Attribute3_A32] is from D_in[Attribute3]
D_out[Attribute3_A34] is from D_in[Attribute3]
D_out[Attribute4_A40] is from D_in[Attribute4]
D_out[Attribute4_A41] is from D_in[Attribute4]
D_out[Attribute4_A410] is from D_in[Attribute4]
D_out[Attribute4_A43] is from D_in[Attribute4]
D_out[Attribute4_A46] is from D_in[Attribute4]
D_out[Attribute4_A48] is from D_in[Attribute4]
D_out[Attribute4_A49] is from D_in[Attribute4]
D_out[Attribute6_A61] is from D_in[Attribute6]
D_out[Attribute6_A62] is from D_in[Attribute6]
D_out[Attribute6_A63] is from D_in[Attribute6]
D_out[Attribute6_A64] is from D_in[Attribute6]
D_out[Attribute6_A65] is from D_in[Attribute6]
D_out[Attribute7_A71] is from D_in[Attribute7]
D_out[Attribute7_A72] is from D_in[Attribute7]
D_out[Attribute7_A74] is from D_in[Attribute7]
D_out[Attribute7_A75] is from D_in[Attribute7]
D_out[Attribute9_A91] is from D_in[Attribute9]
D_out[Attribute9_A92] is from D_in[Attribute9]
D_out[Attribute9_A93] is from D_in[Attribute9]
D_out[Attribute10_A103] is from D_in[Attribute10]
D_out[Attribute12_A121] is from D_in[Attribute12]
D_out[Attribute12_A123] is from D_in[Attribute12]
D_out[Attribute12_A124] is from D_in[Attribute12]
D_out[Attribute14_A141] is from D_in[Attribute14]
D_out[Attribute14_A142] is from D_in[Attribute14]
D_out[Attribute14_A143] is from D_in[Attribute14]
D_out[Attribute15_A151] is from D_in[Attribute15]
D_out[Attribute15_A152] is from D_in[Attribute15]
D_out[Attribute15_A153] is from D_in[Attribute15]
D_out[Attribute17_A172] is from D_in[Attribute17]
D_out[Attribute17_A174] is from D_in[Attribute17]
D_out[Attribute20_A202] is from D_in[Attribute20]